default['dbhost'] = ''
default['dbuser'] = 'root'
default['dbpassword'] = '1234'
default['dbname'] = 'project_management'
default['ext_ip'] = ''
default['es_host'] = ''
default['es_version'] = '6.4.0'
default['modules'] = %w(system prometheus elasticsearch mysql)
default['hosts'] = ''
default['configs'] = %w(rorapp kibana)
